# Generated by Django 3.1.5 on 2021-01-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_price',
            new_name='price',
        ),
    ]
