# Generated by Django 3.1.5 on 2021-01-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0004_auto_20210129_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
