# Generated by Django 3.1.5 on 2021-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0008_auto_20210202_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product'),
            preserve_default=False,
        ),
    ]
