# Generated by Django 3.1.5 on 2021-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0011_auto_20210202_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
