# Generated by Django 3.1.5 on 2021-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0013_auto_20210203_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='adress',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
