# Generated by Django 3.1.5 on 2021-02-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0022_auto_20210205_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='prodotti.OrderItem'),
        ),
    ]
