# Generated by Django 3.1.5 on 2021-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0024_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='prodotti.OrderItem'),
        ),
    ]
