# Generated by Django 3.1.5 on 2021-02-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodotti', '0025_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='opzioni_di_pagamento',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('P', 'PayPal')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodotti.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
